### ISSUE TITLE
Setup PyCharm that testing single modules works

### ISSUE THREAD

**Issue by eega** [eega/ics.py#1]
Traceback (most recent call last):
  File "/home/tom/pycharm-community-2017.3.3/helpers/pycharm/_jb_pytest_runner.py", line 10, in <module>
    from pkg_resources import iter_entry_points
  File "/home/tom/workspace/ics.py/ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/usr/lib/python3.5/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.5/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib/python3.5/email/message.py", line 16, in <module>
    from email import utils
  File "/usr/lib/python3.5/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.5/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/tom/workspace/ics.py/tests/calendar.py", line 4, in <module>
    import arrow
  File "/home/tom/workspace/ics.py/ve/lib/python3.5/site-packages/arrow/__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "/home/tom/workspace/ics.py/ve/lib/python3.5/site-packages/arrow/arrow.py", line 16, in <module>
    from arrow import util, locales, parser, formatter
  File "/home/tom/workspace/ics.py/ve/lib/python3.5/site-packages/arrow/parser.py", line 17, in <module>
    class DateTimeParser(object):
  File "/home/tom/workspace/ics.py/ve/lib/python3.5/site-packages/arrow/parser.py", line 33, in DateTimeParser
    'MMMM': re.compile('({0})'.format('|'.join(calendar.month_name[1:]))),
AttributeError: module 'calendar' has no attribute 'month_name'

**Comment by eega** [comment]
Error caused by pytest test runner setting "Add source roots to PYTHONPATH". PyCharm pytest test runner works if these are unchecked.
